### ISSUE TITLE
Repeated backwards find (F <char>, then semicolon) does not work

### ISSUE THREAD

**Issue by yj-1plusx** [lambdalisue/jupyter-vim-binding#130] opened 2018-07-25 11:10 UTC
### Summary

Backward-searching characters works only once. When I hit semicolon to jump to the next position, instead the curser jumps forward.

### Environment

- [ ] Operating system : ubuntu
- [ ] Web browser : chrome
- [ ] Version or revision of Jupyter Notebook : 5
- [ ] Revision of jupyter-vim-binding : latest master

### Behavior
Backward-searching characters works only once. When I hit semicolon to jump to the next position, instead the curser jumps forward.

#### Expected
Hitting semicolon should make cursor jump backwards to the next occurence 

#### Actual
Cursor jumps forward

**Comment by lambdalisue** [comment] 2018-07-26 05:54
Could not reproduce. 
http://recordit.co/vBP6cUpgS0

Could you try with a different browser?

**Comment by yj-1plusx** [comment] 2018-07-26 08:04
Ah yes sorry, it seems to happen in visual mode only.

**Comment by lambdalisue** [comment] 2018-07-26 11:53
The behavior could be reproduced in https://codemirror.net/demo/vim.html as well.
![](http://g.recordit.co/dmCGReWjr3.gif)
http://recordit.co/dmCGReWjr3

So it must be fixed in CodeMirror. Report issue on https://github.com/codemirror/codemirror/issues?q=is%3Aissue+is%3Aopen+label%3Avim

**Closed as completed by lambdalisue** 2018-07-26 11:53 UTC
