### ISSUE TITLE
Interaction with Scratchpad and Keyboard shortcut editor nbextensions

### ISSUE THREAD

**Issue by omrihar** [lambdalisue/jupyter-vim-binding#83] opened 2016-09-02 11:05 UTC
### Summary

I use the Scratchpad nbextension that opens a quick right pane for quick and dirty code trials before adding code to the main notebook. The extension registers <Ctrl-B> to open it. After installing Vim-binding, however, the <Ctrl-B> launching of Scratchpad no longer works.

I tried to use the Keyboard shortcut editor extension to add this keyboard shortcut again but this extension simply doesn't work when vim-bindings is installed. I'm guessing that because vim-bindings rewrites the keyboard shortcuts dialog this breaks the other extension.

I also tried digging in the source code of both Scratchpad and vim-bindings but I don't understand Jupyter internals enough, unfortunately, to see how I can override the <Ctrl-B> shortcut from vim-bindings and use it for Scratchpad instead. (I don't use <Ctrl-B> in vim anyways so I don't mind losing it).

I guess I could probably make it work if I load Scratchpad after loading vim-bindings but I don't know how to affect the loading order of the extensions either. Any help would be very appreciated!

Thanks,
Omri

EDIT: I now discovered that vim-bindings breaks Scratchpad even further because the Shift-Enter binding (that Scratchpad monkey-patches) is broken.
### Environment
- [ ] Operating system : Arch Linux
- [ ] Web browser : Chrome 49.0.2623.87 (64-bit)
- [ ] Version or revision of Jupyter Notebook : 4.1.0
- [ ] Revision of jupyter-vim-binding : 94769bd

**Comment by lambdalisue** [comment] 2016-09-04 02:52
> EDIT: I now discovered that vim-bindings breaks Scratchpad even further because the Shift-Enter binding (that Scratchpad monkey-patches) is broken.

https://github.com/minrk/nbextension-scratchpad/blob/master/main.js#L44-L57

It seems Scratchpad provides the following shortcuts:
- `scratchpad-execute` (`Shift-Enter`)
- `scratchpad-toggle` (`Ctrl-b`)

So assign that shortcut to `Shift-Enter` with a [Keyboard shortcut editor](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/keyboard_shortcut_editor) would solve the problem I guess.

Or assigning that shortcut to other key would works as well I guess ;-)

**Comment by omrihar** [comment] 2016-09-04 06:59
Hi @lambdalisue, thanks for the quick reply! 
as i wrote in the issue description, it seems that jupyter-vim-binding breaks keyboard shortcut editor as well because it rewrites the keyboard shortcuts screen (at least I didn't manage to use it).

**Comment by lambdalisue** [comment] 2016-09-05 00:34
Oh. I didn't realize that. I'll confirm it and reply the result maybe in this weekend.
I'll likely to forget about the issue so ping me if I don't reply even after the weekend ;-)

**Comment by omrihar** [comment] 2016-09-12 11:39
@lambdalisue Ping ;-)

**Comment by lambdalisue** [comment] 2016-09-15 04:30
Oops sorry.... it may took another week to figure out the way.

Additionally, this issue is equal to #84 so I close this one and continue at #84

**Closed as completed by lambdalisue** 2016-09-15 04:30 UTC

**Comment by DrJimFan** [comment] 2017-11-22 23:42
Good news! Looks like the problem is automatically resolved when you upgrade to Jupyter 5.0.

Run pip install --upgrade notebook or conda upgrade notebook.
